namespace Engine
{
    enum FontSheet
    {
        FONTSHEET_ORIGIN, _CENTRE,
        FONTSHEET_ORIGIN_TOP_LEFT,
        FONTSHEET_ORIGIN_BOTTOM_LEFT,
        FONTSHEET_ORIGIN_TOP_RIGHT,
        FONTSHEET_ORIGIN_BOTTOM_RIGHT
    }
}